name: Automated Release

on:
  push:
    branches:
      - release
      - release-pipeline

jobs:
  release-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Download and install install4j
        run: wget https://download-gcdn.ej-technologies.com/install4j/install4j_linux_8_0_11.deb && sudo dpkg -i install4j_linux_8_0_11.deb
      - name: Build with Gradle
        run: ./gradlew build media -x test
        env:
          INSTALL4J_HOME: /opt/install4j8
          INSTALL4J_LICENSE: ${{ secrets.INSTALL4J_LICENSE }}
      - name: Create a Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/artefacts/**
          name: ${{ github.sha }}
          prerelease: true
